Stage 1: Data analysis and data understanding

In [14]:
#import bib for data analysis
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder
from webencodings import labels
from sklearn.pipeline import Pipeline

from titanic.understand_data import y_pred

1.1 : observation

In [2]:
df = pd.read_csv('train.csv')
print(
    'number of cols in train dataset: \n',
    len(df.columns),#df.shape[1]
    '\n------------------------------------------------\n',
    'number of categorial cols in train dataset: \n',
    df.select_dtypes(exclude=['number']).columns,len(df.select_dtypes(exclude=['number']).columns),
    '\n------------------------------------------------\n',
    'number of numerical cols in train dataset: \n',
    df.select_dtypes(include=['number']).columns,len(df.select_dtypes(include=['number']).columns),
    '\n------------------------------------------------\n',
    'number of data row in the dataset: \n',
    df.shape[0]#len(df)
)

number of cols in train dataset:
 15
------------------------------------------------
 number of categorial cols in train dataset:
 Index(['Gender', 'City_Type', 'Current_Car_Type', 'Home_Charging_Possible',
       'Subsidy_Available', 'Range_Anxiety_Level', 'Will_Buy_EV'],
      dtype='str') 7
------------------------------------------------
 number of numerical cols in train dataset:
 Index(['id', 'Age', 'Annual_Income_USD', 'Daily_Commute_km',
       'Number_of_Cars_Owned', 'Charging_Stations_Near_Home',
       'Charging_Stations_Near_Work', 'Environmental_Concern_Level'],
      dtype='str') 8
------------------------------------------------
 number of data row in the dataset:
 668665

from here i undestand many thing altough i didn't finish my observation,
first , the dataset is too long ,usually kaggle put at maximum 10'000 but now they put more then half of a million so i cauld say that they prerotize efficiency
second , we need to remember that the goal is to predict Electric Vehicle Interest so the model will be progression model because we have continue prediction
next, i will see some general info

In [3]:
#df.set_index('id', inplace=True)
df.head()

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV
0,0,66,92887.0,23.4,2,3,7,1.0,Male,Suburban,Sedan,Yes,No,Low,No
1,1,38,30000.0,5.0,1,2,2,4.0,Male,Rural,SUV,Yes,No,Low,No
2,2,26,94389.0,36.8,1,8,15,5.0,Female,Urban,Sedan,No,Yes,Low,Yes
3,3,66,73580.0,23.7,2,6,9,3.0,Male,Suburban,Hatchback,Yes,No,Low,No
4,4,54,57898.0,50.8,1,2,3,3.0,Male,Suburban,Hatchback,Yes,No,Low,No

In [4]:
#let's see more about the dataset
print(
    '----------------------------------\n',
    df.info(),
    '\n------------------------------\n',
    df.isna().sum(),
    '\n------------------------------\n',
)

<class 'pandas.DataFrame'>
RangeIndex: 668665 entries, 0 to 668664
Data columns (total 15 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   id                           668665 non-null  int64
 1   Age                          668665 non-null  int64
 2   Annual_Income_USD            668665 non-null  float64
 3   Daily_Commute_km             668665 non-null  float64
 4   Number_of_Cars_Owned         668665 non-null  int64
 5   Charging_Stations_Near_Home  668665 non-null  int64
 6   Charging_Stations_Near_Work  668665 non-null  int64
 7   Environmental_Concern_Level  668665 non-null  float64
 8   Gender                       668665 non-null  str
 9   City_Type                    668665 non-null  str
 10  Current_Car_Type             668665 non-null  str
 11  Home_Charging_Possible       668665 non-null  str
 12  Subsidy_Available            668665 non-null  str
 13  Range_Anxiety_Level          668665 non-null  str
 14  Will_Buy_EV                  668665 non-null  str
dtypes: float64(3), int64(5), str(7)
memory usage: 76.5 MB
----------------------------------
 None
------------------------------
 id                             0
Age                            0
Annual_Income_USD              0
Daily_Commute_km               0
Number_of_Cars_Owned           0
Charging_Stations_Near_Home    0
Charging_Stations_Near_Work    0
Environmental_Concern_Level    0
Gender                         0
City_Type                      0
Current_Car_Type               0
Home_Charging_Possible         0
Subsidy_Available              0
Range_Anxiety_Level            0
Will_Buy_EV                    0
dtype: int64
------------------------------

wow this so unusual from kaggle the dataset doesn't has any null value , let's check something else

In [5]:
df.describe()

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level
count,668665.000000,668665.000000,668665.000000,668665.000000,668665.000000,668665.000000,668665.000000,668665.000000
mean,334332.000000,47.039171,84769.266989,32.158298,1.712626,4.960408,7.176314,2.935477
std,193027.103211,12.875448,28648.029042,18.730474,0.729275,3.926843,5.186627,1.429119
min,0.000000,25.000000,30000.000000,5.000000,1.000000,0.000000,0.000000,1.000000
25%,167166.000000,36.000000,67376.000000,17.200000,1.000000,2.000000,3.000000,2.000000
50%,334332.000000,47.000000,84880.000000,33.600000,2.000000,4.000000,6.000000,3.000000
75%,501498.000000,58.000000,102753.000000,47.400000,2.000000,7.000000,10.000000,4.000000
max,668664.000000,69.000000,188549.000000,98.700000,4.000000,14.000000,19.000000,5.000000

In [6]:
for i in df.select_dtypes(exclude=['number']).columns.values:
    print(df[i].unique())

<StringArray>
['Male', 'Female', 'Other']
Length: 3, dtype: str
<StringArray>
['Suburban', 'Rural', 'Urban']
Length: 3, dtype: str
<StringArray>
['Sedan', 'SUV', 'Hatchback', 'Truck']
Length: 4, dtype: str
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
<StringArray>
['Low', 'Medium', 'High']
Length: 3, dtype: str
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [7]:
for i in df.columns.values: #df.apply(lamda x: x.unique())
    print('----------------------------------------------------\n')
    print(i)
    print(df[i].unique(),'nunique:',df[i].nunique())

----------------------------------------------------

id
[     0      1      2 ... 668662 668663 668664] nunique: 668665
----------------------------------------------------

Age
[66 38 26 54 50 55 45 39 57 25 65 59 36 51 41 32 48 46 60 28 68 56 49 67
 43 29 42 31 58 35 53 37 34 47 52 69 63 64 40 30 62 61 33 44 27] nunique: 45
----------------------------------------------------

Annual_Income_USD
[ 92887.  30000.  94389. ... 123813. 121432.  86857.] nunique: 13214
----------------------------------------------------

Daily_Commute_km
[23.4  5.  36.8 23.7 50.8 55.1 42.9 52.2 31.5 66.9 27.6 47.4 33.3 19.5
 44.5 35.4 76.4 25.4 18.6 36.2 49.4 20.1 42.7 32.6 54.8 25.8 50.6 48.
 32.  31.  29.8 13.2 45.4 41.3 37.7 21.  11.2 45.9 28.5 39.6 30.4 34.4
 57.7 52.1 59.  22.  33.4 47.1 37.2 33.6 26.5 54.3 53.2 61.1 47.2 37.5
 57.2 52.  12.8 28.3 57.1 12.7 41.2 48.7 45.8 43.9 37.1 39.3 51.2 64.6
 49.2 36.  47.9 43.6 49.3 48.9 49.1 11.7 43.3 18.8 27.9 30.9 24.4 22.4
 35.7 66.6 58.9 27.5 30.1 49.  28.4 65.1 55.7 32.1 71.3 50.4 40.9 58.8
 61.4 29.2 16.2 57.4 26.9 46.7 49.5 29.5 32.4 42.1 32.7 46.2 43.2 54.4
 38.3 26.  26.6 56.5 33.5 40.4 31.4 52.4 26.7 25.2 54.5 63.9 29.3 21.3
 38.9 40.3 19.7 24.2 41.7 37.4 60.7 29.  46.6 16.3 22.2 31.3 34.  25.
 67.5 54.1 62.4 44.  34.7 52.5 35.2 30.5 43.1 29.4 28.  20.  61.8 38.1
 17.6 50.  35.3 70.9 66.  30.2 39.7 40.  38.8 30.3 21.7 55.3 38.  28.7
 40.6 49.7 53.7 34.3 48.5 21.1 50.3 42.4 43.5 17.1 40.1 51.8 62.1 22.6
 56.  50.7 53.  47.  44.7 46.3 52.8 39.1 18.5 34.1 71.4 38.5 47.8 22.7
 39.4 31.7 44.3 52.6 48.2 36.3 51.  30.  44.4 16.9 23.6 25.9 55.4 30.6
 45.1 33.7 47.5 60.4 27.7 24.6 23.2 21.8 54.7 31.8 56.6 27.3 24.5 33.1
 20.2 45.3 46.8 19.9 38.7 35.8 27.  46.4 40.5 33.2 32.3 20.7 27.2 56.4
 42.  37.3 64.7 15.4 56.9 34.8 16.  49.9 67.4 17.2 60.8 44.9 62.  50.2
 55.  28.9 18.9 17.8 29.1 28.6 41.5 60.3 42.3 61.  23.9 58.7 37.8 33.
 58.4 47.3 67.6 42.2 18.1 32.2 59.9 24.8 21.5 51.1 57.  51.9 45.2 36.4
 46.5 12.3 16.6 44.1 59.2 36.7 55.5 39.5 11.  43.7 18.3 20.4 31.6 27.1
 31.9 41.6 15.3 47.6 59.7 46.  33.9 34.2 32.5 22.9 29.7 13.  48.1 59.5
 19.8 30.7 13.5 26.8 56.1 34.5 61.5 13.1 54.  55.6 36.5 21.2 49.6 26.4
 32.9 25.7 35.1 28.8 11.6 41.  43.8 21.9 69.8 45.7 36.9 44.2 59.4 43.4
 53.6 58.2 62.8 61.9 48.4 17.4 33.8 50.1 59.6 23.1 19.  19.4 53.4 22.3
 41.9 38.2 60.2 66.3 38.6 67.9 46.1 51.5 25.6 34.6 12.1 22.5 45.  36.1
 76.5 24.3 52.3 39.9 25.3 51.7 42.8 18.7 23.5 52.9 24.9  5.7 32.8 57.6
 52.7 69.5 34.9 39.8 27.4 58.3 18.2 42.6 53.1 53.3 53.9 56.8 64.9 50.9
 70.4 66.5 48.3 58.5 14.8 79.2 10.2 23.3 27.8 37.  26.1 40.7 55.9 46.9
 35.6 65.2 15.9 31.1 20.6 56.3 64.2 55.8 44.6 26.2 56.7 71.  17.7 48.6
 47.7 50.5 31.2 20.8 65.  69.6 60.5 17.3 16.7 70.2 36.6 22.8 15.2 66.8
 18.4 63.  65.4 54.9 29.9 12.6 39.  45.6 41.1 37.6 70.6 41.4 22.1 16.8
 35.  41.8 17.9 14.2 37.9 40.8  8.9 53.5 60.  70.5 62.3 26.3 53.8 24.7
 57.9 40.2  5.6 75.1 63.2 65.5 57.3 29.6 19.1 35.9 58.6 25.1 66.1 68.2
 67.1 57.5 63.5 51.6 61.6 69.  44.8 45.5 12.2 20.5 20.9 28.2 49.8 67.2
 48.8 55.2 21.6 58.  12.9 76.  58.1 59.1 15.7 79.7 17.  42.5 51.4 60.1
 16.4 67.7  5.8 25.5 16.1 19.6 61.3 59.3 28.1 63.8 15.5 21.4 13.9 12.
 69.2 14.6 67.3 15.  66.7 12.5  9.5 80.3 11.5 51.3 24.  64.8 15.1  7.4
 54.6 54.2 13.7 17.5 20.3 13.8 67.8 83.5 62.7 19.2 12.4 11.9 70.7 13.4
 70.3 60.9 62.2 11.1 64.4 70.8 30.8 62.9 11.8 11.3 39.2 71.2 24.1 74.4
 59.8 43.  88.2 16.5 13.6 62.6 67.  19.3 71.9 61.7  8.2 98.2 78.5  5.4
 64.1 70.1 38.4 60.6 78.  71.8 10.6 62.5 11.4  9.8 82.7 35.5 15.6 61.2
 76.2  8.  65.6 65.9 23.8 56.2 70.   7.  10.3 76.1 78.7 68.3 68.1 69.4
 10.9 10.1 69.7 69.9 18.  68.6 66.4 64.3 23.  71.5 66.2 14.9 63.7 63.4
 68.5 15.8 68.8 57.8 76.7 90.6 14.3  8.7 64.5  8.5  8.4 76.3 68.9 68.4
  9.9 71.1 65.3 10.8 79.1 14.5 13.3  5.5 63.1 68.7 69.1 10.4 76.8 79.5
  7.3 71.6 10.5 63.3 75.5 63.6 79.6  5.1 75.7 76.6 88.5  9.4 64.   5.3
 14.7  9.3 75.3 76.9 14.4 78.9  7.6 14.  74.7 74.5 79.3 86.5 65.8 74.
  7.7  9.1 69.3  7.9  8.6 74.2  9.7 71.7  9.2  5.9 68.  75.2 88.9 85.5
 79.9  7.2 78.1 83.4 79.4 89.6 74.8 10.   8.8 74.9  9.6 79.  75.4 75.8
 88.7 65.7 78.8 96.3 78.4 82.9 75.  81.5  5.2 10.7 78.3 78.6 80.6 84.1
 79.8 88.6 96.5  8.1 86.3 96.7 14.1 72.9 74.3 83.7 87.1 82.8 78.2  8.3
 96.4 75.6 74.1 87.5 74.6 82.1 80.2 86.2 72.5 92.5 83.8 80.5 89.4 89.2
 77.9 89.3 83.  83.6 86.8 81.  85.2  7.8 96.6 88.3 72.7  7.5 73.1 75.9
  7.1 85.  73.4 92.  98.7  9.  84.4 88.8 86.6 84.2 98.3 89.  82.5 89.8
 85.3 84.7 77.8 84.9 89.1 83.9 92.2 87.4  6.  73.8 96.  89.7 88.  87.2
 73.6 84.8 87.9 81.2 98.4 88.4 83.1 81.3 77.  98.1 84.3 73.9 73.5 81.8
 85.7 72.6 87.  80.4 96.2 73.7 86. ] nunique: 805
----------------------------------------------------

Number_of_Cars_Owned
[2 1 4 3] nunique: 4
----------------------------------------------------

Charging_Stations_Near_Home
[ 3  2  8  6  1 13 11  0  9  7 10  4  5 14 12] nunique: 15
----------------------------------------------------

Charging_Stations_Near_Work
[ 7  2 15  9  3  5  1 17 18 11 16 12 14 13 10  0  8 19  4  6] nunique: 20
----------------------------------------------------

Environmental_Concern_Level
[1. 4. 5. 3. 2.] nunique: 5
----------------------------------------------------

Gender
<StringArray>
['Male', 'Female', 'Other']
Length: 3, dtype: str nunique: 3
----------------------------------------------------

City_Type
<StringArray>
['Suburban', 'Rural', 'Urban']
Length: 3, dtype: str nunique: 3
----------------------------------------------------

Current_Car_Type
<StringArray>
['Sedan', 'SUV', 'Hatchback', 'Truck']
Length: 4, dtype: str nunique: 4
----------------------------------------------------

Home_Charging_Possible
<StringArray>
['Yes', 'No']
Length: 2, dtype: str nunique: 2
----------------------------------------------------

Subsidy_Available
<StringArray>
['No', 'Yes']
Length: 2, dtype: str nunique: 2
----------------------------------------------------

Range_Anxiety_Level
<StringArray>
['Low', 'Medium', 'High']
Length: 3, dtype: str nunique: 3
----------------------------------------------------

Will_Buy_EV
<StringArray>
['No', 'Yes']
Length: 2, dtype: str nunique: 2

now let twick our data a little bit more to make the work of the model a little bit easier, as you can see we change some col to bool

In [60]:
def clean_data_pipeline(link):
    return (pd.read_csv(link).pipe(lambda x: x.set_index('id'))
 .pipe(lambda x: x.assign(Gender = [True if i == 'Male' else False for i in x['Gender']]))
 .pipe(lambda x: x.assign(Home_Charging_Possible =[True if i == 'Yes' else False for i in x['Home_Charging_Possible']] ))
 .pipe(lambda x: x.assign(Subsidy_Available = [True if i == 'Yes' else False for i in x['Subsidy_Available']] ))
 #.pipe(lambda x: x.assign(Will_Buy_EV = [True if i == 'Yes' else False for i in x['Will_Buy_EV']]))
 .pipe(lambda x: x.assign(City_Type = x['City_Type'].str[0])))

In [9]:
df = clean_data_pipeline('train.csv')
df.head()

,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV
id,,,,,,,,,,,,,,
0,66,92887.0,23.4,2,3,7,1.0,True,S,Sedan,True,False,Low,False
1,38,30000.0,5.0,1,2,2,4.0,True,R,SUV,True,False,Low,False
2,26,94389.0,36.8,1,8,15,5.0,False,U,Sedan,False,True,Low,True
3,66,73580.0,23.7,2,6,9,3.0,True,S,Hatchback,True,False,Low,False
4,54,57898.0,50.8,1,2,3,3.0,True,S,Hatchback,True,False,Low,False

ok i guess we are ready to start by the model creation , i hope we can do good

In [71]:
from sklearn.model_selection import train_test_split, KFold, StratifiedKFold

X = df.drop('Will_Buy_EV', axis=1)#.iloc[0:28000]
y = df['Will_Buy_EV']#.iloc[0:28000]
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=7)
cat = X.select_dtypes(exclude=['number','bool']).columns.values
num = X.select_dtypes(include=['number']).columns.values
boolC = X.select_dtypes(include=['bool']).columns.values

In [12]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder


models = {
'LR':LogisticRegression(),
'DTC':DecisionTreeClassifier(),
'RFC':RandomForestClassifier(),
}

preprocessor = ColumnTransformer(
    transformers=[
        ('cat',OneHotEncoder(handle_unknown='ignore'),cat)
    ]
)

result = []
kf = KFold(n_splits=5, random_state=7 ,shuffle=True)
for i in models:
    model = Pipeline(steps=[('preprocessor',preprocessor),
                            ('model',models[i])])
    cv_results = cross_val_score(model, X_train, y_train, cv=kf)
    result.append(cv_results)
print(result)
plt.boxplot(result, tick_labels=models.keys())
plt.show()

KeyboardInterrupt:

i think i will choose LogisticRegression or one of his decendent (lasso or ridge)

In [72]:
from sklearn.preprocessing import StandardScaler

preprocessor = ColumnTransformer(
    transformers=[
        ('cat',OneHotEncoder(handle_unknown='ignore'),cat),
        ('num', StandardScaler(), num),
         ('bool', 'passthrough', boolC)
    ]
)
model = Pipeline(steps=[('preprocessor',preprocessor),('model',LogisticRegression(max_iter=1000))])
model.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  <StringArray>
['City_Type', 'Current_Car_Type', 'Range_Anxiety_Level']
Length: 3, dtype: str),
                                                 ('num', StandardScaler(),
                                                  <StringArray>
[                        'Age',           'Annual_Income_USD',
            'Daily_Commute_km',        'Number_of_Cars_Owned',
 'Charging_Stations_Near_Home', 'Charging_Stations_Near_Work',
 'Environmental_Concern_Level']
Length: 7, dtype: str),
                                                 ('bool', 'passthrough',
                                                  <StringArray>
['Gender', 'Home_Charging_Possible', 'Subsidy_Available']
Length: 3, dtype: str)])),
                ('model', LogisticRegression(max_iter=1000))])

In [51]:

y_pred = model.predict_proba(X_test)
print(y_pred[:,1])

[0.17893895 0.20544903 0.17893895 ... 0.1886138  0.03924386 0.04144969]

In [74]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
y_pred = model.predict(X_test)
y_pred = (y_pred >= 0.5).astype(int)
cm = confusion_matrix(y_test,y_pred)
classification_report(y_test,y_pred)
print('accuracy:',accuracy_score(y_test,y_pred))
print(cm)
print(classification_report(y_test,y_pred))

accuracy: 0.8946557693314291
[[104178   6071]
 [  8017  15467]]
              precision    recall  f1-score   support

       False       0.93      0.94      0.94    110249
        True       0.72      0.66      0.69     23484

    accuracy                           0.89    133733
   macro avg       0.82      0.80      0.81    133733
weighted avg       0.89      0.89      0.89    133733

In [85]:
X_test_sub = clean_data_pipeline('test.csv')
y_pred_proba = grid.predict_proba(X_test_sub)

sub = pd.DataFrame(
    {
        'id':X_test_sub.index,
        'Will_Buy_EV':y_pred_proba[:,1],
    }
)
sub.to_csv('submission.csv',index=False)

In [68]:
logr = model.named_steps['model']
logr.coef_[0]

array([-0.52888799, -0.5783676 , -0.6428778 , -0.41322822, -0.37304671,
       -0.43003051, -0.53382794, -2.70628893,  1.31526412, -0.35910858])

In [83]:
from sklearn.model_selection import cross_val_score, StratifiedKFold
cv = StratifiedKFold(n_splits=5, random_state=260422 ,shuffle=True)
score = cross_val_score(grid, X, y, cv=cv,scoring='roc_auc',n_jobs=-1)

In [84]:
print(score)
print('mean score:',score.mean())

[0.9382647  0.93814572 0.93789392 0.9375341  0.9386498 ]
mean score: 0.938097647352647

In [82]:
from sklearn.model_selection import GridSearchCV
params ={
    'model__C': [0.001, 0.01, 0.1, 0.3, 1, 3, 10, 30, 100]
}
grid = GridSearchCV(
    model,
    param_grid=params,
    scoring='roc_auc',
    cv=cv,
    n_jobs=-1,
)
grid.fit(X,y)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=260422, shuffle=True),
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         <StringArray>
['City_Type', 'Current_Car_Type', 'Range_Anxiety_Level']
Length: 3, dtype: str),
                                                                        ('num',
                                                                         StandardScaler(),
                                                                         <StringArray>
[                        'Age',           'Annual_Income_USD',
            'D...
 'Charging_Stations_Near_Home', 'Charging_Stations_Near_Work',
 'Environmental_Concern_Level']
Length: 7, dtype: str),
                                                                        ('bool',
                                                                         'passthrough',
                                                                         <StringArray>
['Gender', 'Home_Charging_Possible', 'Subsidy_Available']
Length: 3, dtype: str)])),
                                       ('model',
                                        LogisticRegression(max_iter=1000))]),
             n_jobs=-1,
             param_grid={'model__C': [0.001, 0.01, 0.1, 0.3, 1, 3, 10, 30,
                                      100]},
             scoring='roc_auc')

In [ ]:
from sklearn.svm import SV